apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "safasfasfaf"
  description: "safasfasfaf"
  annotations:
    github.com/project-slug: NishkarshRaj/safasfasfaf
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/safasfasfaf"